newIssueWelcomeComment: >
  Hey! Welcome to Doc2pen ðŸ™
  We can see you have raised your first issue. Well, Congratulations!
  The maintainersðŸ¤“ will get back to you as per their availibility and reviewðŸ” your issue. 
  Till then please be patientðŸ˜Š.

newPRWelcomeComment: >
  Hey! Welcome to Doc2pen ðŸ™
  Thanks for raising this PR!
  The maintainersðŸ¤“ will get back to you as per their availibility and reviewðŸ” your issue. 
  Till then please be patientðŸ˜Š.

firstPRMergeComment: >
  Congratulations on getting your first PR merged!.
  ![](https://media.giphy.com/media/3oz9ZE2Oo9zRC/giphy.gif)
